# Generated by Django 3.2.9 on 2021-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211102_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='name_genitive',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название в родительном падеже'),
        ),
        migrations.AddField(
            model_name='measure',
            name='name_genitive_plural',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название в родительном падеже множественного числа'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название в родительном падеже'),
        ),
    ]
